### ISSUE TITLE
hotpot-paragraph-4.min.tsv.

### ISSUE THREAD

**Issue by niuniuz** [zycdev/AISO#1]
Where can I get the file hotpot-paragraph-4.min.tsv.

 CUDA_VISIBLE_DEVICES=1,2,3 python -m torch.distributed.launch --nproc_per_node=3 train_union.py
**--corpus_path data/corpus/hotpot-paragraph-4.min.tsv**
 --train_file data/hotpot-step-train.jsonl
 --predict_file data/hotpot-step-dev.jsonl
 --do_train
 --do_predict
 --encoder_name google/electra-base-discriminator
 --init_checkpoint ""
 --hard_negs_per_state 2
 --memory_size 2
 --max_distractors 2
 --num_workers 1
 --cmd_dropout_prob 0
 --sp_weight 0.05
 --per_gpu_train_batch_size 8
 --learning_rate 5e-5
 --warmup_ratio 0.1
 --num_train_epochs 100
 --eval_period -1
 --criterion_metric action_acc
 --tag no-early-answer
 --debug

**Comment by niuniuz** [comment]
> Where can I get the file hotpot-paragraph-4.min.tsv.

> CUDA_VISIBLE_DEVICES=1,2,3 python -m torch.distributed.launch --nproc_per_node=3 train_union.py \
    --corpus_path data/corpus/hotpot-paragraph-4.min.tsv \
    --train_file data/hotpot-step-train.jsonl \
    --predict_file data/hotpot-step-dev.jsonl \
    --do_train \
    --do_predict \
    --encoder_name google/electra-base-discriminator \
    --init_checkpoint "" \
    --hard_negs_per_state 2 \
    --memory_size 2 \
    --max_distractors 2 \
    --num_workers 1 \
    --cmd_dropout_prob 0 \
    --sp_weight 0.05 \
    --per_gpu_train_batch_size 8 \
    --learning_rate 5e-5 \
    --warmup_ratio 0.1 \
    --num_train_epochs 100 \
    --eval_period -1 \
    --criterion_metric action_acc \
    --tag no-early-answer \
    --debug

**Comment by niuniuz** [comment]
> > Where can I get the file hotpot-paragraph-4.min.tsv.
> 
> > CUDA_VISIBLE_DEVICES=1,2,3 python -m torch.distributed.launch --nproc_per_node=3 train_union.py 
> >     **--corpus_path data/corpus/hotpot-paragraph-4.min.tsv** 
> >     --train_file data/hotpot-step-train.jsonl 
> >     --predict_file data/hotpot-step-dev.jsonl 
> >     --do_train 
> >     --do_predict 
> >     --encoder_name google/electra-base-discriminator 
> >     --init_checkpoint "" 
> >     --hard_negs_per_state 2 
> >     --memory_size 2 
> >     --max_distractors 2 
> >     --num_workers 1 
> >     --cmd_dropout_prob 0 
> >     --sp_weight 0.05 
> >     --per_gpu_train_batch_size 8 
> >     --learning_rate 5e-5 
> >     --warmup_ratio 0.1 
> >     --num_train_epochs 100 
> >     --eval_period -1 
> >     --criterion_metric action_acc 
> >     --tag no-early-answer 
> >     --debug

**Comment by zycdev** [comment]
Thanks for your interest. The command you referenced is a legacy command for debugging. Please use this [command](https://github.com/zycdev/AISO/blob/main/train_union.py#L55) without `--debug` to train the model. I have uploaded some processed data to [Google Driver](https://drive.google.com/drive/folders/1n38_RIhz5jyZQUFLkp-QUVERhAI7E6nn?usp=sharing). But it may be incomplete so far, I will update these in my free time.
