### ISSUE TITLE
Data used

### ISSUE THREAD

**Issue by timhartill** [zycdev/AISO#2]
Hi, thank you for posting your code. I am trying to get train_union.py to work. Initially I tried to get it to work using the corpus file proved in the google drive link (https://github.com/zycdev/AISO/issues/1). However that file is truncated and also doesn't appear to be the same wikipedia version as the original hotpotqa abstracts. So I've recreated the corpus file from the original HotpotQA abstracts. 

Unfortunately when now I look in the dev and train jsonl step files provided from the google drive link, a few of the samples have paragraph ids in the  ['hard_negs'] and  ['state2action']['initial']['sp_ranks'] keys that don't match the Hotpotqa abstracts corpus, specifically they end in '_1' or '_-1' instead of '_0'. Can you please advise where I can get these paragraphs from or alternatively provide an updated set of data?

**Comment by Avo-k** [comment]
did you manage to get it to work somehow ?
